bucket_name = "cloud-oriented-arch-course-src-bucket"
project_id = "cloud-oriented-arch-course"
region  = "europe-west1"
mailgun_domain = "sandboxa25a788df9fe48608631dad560a0bcf3.mailgun.org"
topic_name = "booking-events"
admin_email = "dolris@ukr.net"
alert_email = "dolris@ukr.net"
watchdog_timeout_minutes = 30
watchdog_schedule        = "*/5 * * * *"